version: '3'

services:
  backend:
    container_name: nest_api
    build: nest-api
    ports:
      - '3000:3000'

  frontend:
    container_name: frontend
    build: frontend
    ports:
      - '3001:3001'
    depends_on:
      - backend
